pca_item_cost_class <- function(con) {
  #extract raw data
  raw_data <- dplyr::tbl(con,
                         from = dbplyr::in_schema("AML", "PCA_MY_FY_CY_FACT")) |>
    dplyr::filter(MONTH_TYPE %in% c("FY"),!YEAR_DESC %in% c("2013/2014", "2014/2015")) |>
    dplyr::select(
      "YEAR_DESC",
      "PRESC_PREP_CLASS",
      "DISP_PREP_CLASS",
      "ITEM_COUNT",
      "ITEM_PAY_DR_NIC"
    ) |>
    dplyr::group_by(YEAR_DESC) |>
    dplyr:: summarise(
      # CREATE ITEM VARIABLES
      PRESC_GEN_ITEMS = sum(ITEM_COUNT[PRESC_PREP_CLASS %in% c("01","02","05")]),
      PRESC_DISP_GEN_ITEMS = sum(ITEM_COUNT[PRESC_PREP_CLASS %in% c("01","02","05") & DISP_PREP_CLASS %in% c("01","05")]),
      PRESC_GEN_DISP_PROP_ITEMS = sum(ITEM_COUNT[PRESC_PREP_CLASS %in% c("01","02","05") & DISP_PREP_CLASS %in% c("02","03")]),
      PRESC_DISP_PROP_ITEMS = sum(ITEM_COUNT[PRESC_PREP_CLASS == "03" & DISP_PREP_CLASS == "03"]),
      APPLIANCE_ITEMS = sum(ITEM_COUNT[DISP_PREP_CLASS == "04"]),
      TOTAL_ITEMS = sum(ITEM_COUNT),
      # CREATE COST VARIABLES
      PRESC_GEN_NIC = sum((ITEM_PAY_DR_NIC[PRESC_PREP_CLASS %in% c("01","02","05")])/100),
      PRESC_DISP_GEN_NIC = sum((ITEM_PAY_DR_NIC[PRESC_PREP_CLASS %in% c("01","02","05") & DISP_PREP_CLASS %in% c("01","05")])/100),
      PRESC_GEN_DISP_PROP_NIC = sum((ITEM_PAY_DR_NIC[PRESC_PREP_CLASS %in% c("01","02","05") & DISP_PREP_CLASS %in% c("02","03")])/100),
      PRESC_DISP_PROP_NIC = sum((ITEM_PAY_DR_NIC[PRESC_PREP_CLASS == "03" & DISP_PREP_CLASS == "03"])/100),
      APPLIANCE_NIC = sum((ITEM_PAY_DR_NIC[DISP_PREP_CLASS == "04"])/100),
      TOTAL_NIC = sum(ITEM_PAY_DR_NIC/100)
    ) |>
    
    dplyr:: mutate(
      PRESC_GEN_ITEMS_PER = PRESC_GEN_ITEMS/TOTAL_ITEMS*100,
      PRESC_DISP_GEN_ITEMS_PER = PRESC_DISP_GEN_ITEMS/TOTAL_ITEMS*100,
      PRESC_GEN_DISP_PROP_ITEMS_PER = PRESC_GEN_DISP_PROP_ITEMS/TOTAL_ITEMS*100,
      PRESC_DISP_PROP_ITEMS_PER = PRESC_DISP_PROP_ITEMS/TOTAL_ITEMS*100,
      APPLIANCE_ITEMS_PER = APPLIANCE_ITEMS/TOTAL_ITEMS*100,
      
      PRESC_GEN_NIC_PER = PRESC_GEN_NIC/TOTAL_NIC*100,
      PRESC_DISP_GEN_NIC_PER = PRESC_DISP_GEN_NIC/TOTAL_NIC*100,
      PRESC_GEN_DISP_PROP_NIC_PER = PRESC_GEN_DISP_PROP_NIC/TOTAL_NIC*100,
      PRESC_DISP_PROP_NIC_PER = PRESC_DISP_PROP_NIC/TOTAL_NIC*100,
      APPLIANCE_NIC_PER = APPLIANCE_NIC/TOTAL_NIC*100
      
    ) |>
    dplyr::mutate(
      # MEASURES
      PRESC_GEN_COST_PER_ITEM = PRESC_GEN_NIC/PRESC_GEN_ITEMS,
      PRESC_DISP_GEN_COST_PER_ITEM = PRESC_DISP_GEN_NIC/PRESC_DISP_GEN_ITEMS,
      PRESC_GEN_DISP_PROP_COST_PER_ITEM = PRESC_GEN_DISP_PROP_NIC/PRESC_GEN_DISP_PROP_ITEMS,
      PRESC_DISP_PROP_COST_PER_ITEM = PRESC_DISP_PROP_NIC/PRESC_DISP_PROP_ITEMS,
      APPLIANCE_COST_PER_ITEM = APPLIANCE_NIC/APPLIANCE_ITEMS,
      TOTAL_COST_PER_ITEM = TOTAL_NIC/TOTAL_ITEMS
    ) |>
    dplyr::ungroup()
  #pull data from warehouse
  data <- raw_data |>
    collect	()
  table <- data |>
    dplyr::select(
      "YEAR_DESC",
      "PRESC_GEN_ITEMS",
      "PRESC_DISP_GEN_ITEMS",
      "PRESC_GEN_DISP_PROP_ITEMS",
      "PRESC_DISP_PROP_ITEMS",
      "APPLIANCE_ITEMS",
      "TOTAL_ITEMS",
      "PRESC_GEN_ITEMS_PER",
      "PRESC_DISP_GEN_ITEMS_PER",
      "PRESC_GEN_DISP_PROP_ITEMS_PER",
      "PRESC_DISP_PROP_ITEMS_PER",
      "APPLIANCE_ITEMS_PER",
      # COSTS
      "PRESC_GEN_NIC",
      "PRESC_DISP_GEN_NIC",
      "PRESC_GEN_DISP_PROP_NIC",
      "PRESC_DISP_PROP_NIC",
      "APPLIANCE_NIC",
      "TOTAL_NIC",
      "PRESC_GEN_NIC_PER",
      "PRESC_DISP_GEN_NIC_PER",
      "PRESC_GEN_DISP_PROP_NIC_PER",
      "PRESC_DISP_PROP_NIC_PER",
      "APPLIANCE_NIC_PER",
      # MEASURES
      "PRESC_GEN_COST_PER_ITEM",
      "PRESC_DISP_GEN_COST_PER_ITEM",
      "PRESC_GEN_DISP_PROP_COST_PER_ITEM",
      "PRESC_DISP_PROP_COST_PER_ITEM",
      "APPLIANCE_COST_PER_ITEM",
      "TOTAL_COST_PER_ITEM")    |>
    dplyr::arrange(YEAR_DESC)
  return(table)
}

