publication_name: "Prescription Cost Analysis"
publication_sub_name: "England 2024/25"
publication_date: "5 June 2025"
responsible_statistician: "Graham Platten"
scotland_pca: "https://publichealthscotland.scot/media/29355/prescription_cost_analysis_2024.xlsx"
ni_pca: "Y:/Official Stats/PCA/data/NI_PCA_2024.xlsx"
ni_pca_link: "https://bso.hscni.net/directorates/operations/family-practitioner-services/directorates-operations-family-practitioner-services-information-unit/general-pharmaceutical-services-and-prescribing-statistics/prescription-cost-analysis/"
wa_pca: "Y:/Official Stats/PCA/data/PCA_Wales_202324.xlsx"
wa_pca_link: "https://nwssp.nhs.wales/ourservices/primary-care-services/general-information/data-and-publications/prescription-cost-analysis/"
fy_nat_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_summary_tables_2024_25_v001.xlsx"
fy_icb_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_icb_summary_tables_2024_25_v001.xlsx"
add_anl_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_additional_tables_2024_25_v001.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_background_info_methodology_june2025_v001.html"
nhsbsa_pca_link: "https://www.nhsbsa.nhs.uk/prescription-data/dispensing-data/prescription-cost-analysis-pca-data"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
