publication_name: "Prescription Cost Analysis"
publication_sub_name: "England 2023/24"
publication_date: "6 June 2024"
responsible_statistician: "Graham Platten"
scotland_pca: "https://publichealthscotland.scot/media/21843/prescription_cost_analysis_2023.xlsx"
ni_pca: "Y:/Official Stats/PCA/data/NI_PCA_2023.xlsx"
ni_pca_link: "https://bso.hscni.net/wp-content/uploads/2024/02/PCA_2023.xlsx"
wa_pca: "Y:/Official Stats/PCA/data/PCA_Wales_202223.xlsx"
wa_pca_link: "https://www.gov.wales/sites/default/files/statistics-and-research/2023-11/prescriptions-summary-data-2001-02-to-2022-23-011.ods"
fy_nat_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_summary_tables_2023_24_v001.xlsx"
fy_icb_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_icb_summary_tables_2023_24_v001.xlsx"
add_anl_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_additional_tables_2023_24_v001.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_background_info_methodology_v001.html"
nhsbsa_pca_link: "https://www.nhsbsa.nhs.uk/prescription-data/dispensing-data/prescription-cost-analysis-pca-data"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
