publication_name: "Prescription Cost Analysis"
publication_sub_name: "England 2022/23"
publication_date: "8 June 2023"
responsible_statistician: "Graham Platten"
scotland_pca: "https://publichealthscotland.scot/media/14993/prescription_cost_analysis_2022.xlsx"
ni_pca: "https://hscbusiness.hscni.net/pdf/Prescription%20Cost%20Analysis%20-%202022.xlsx"
wa_pca: "Y:/Official Stats/PCA/data/PCA_Wales_202122.xlsx"
