publication_name: "Prescription Cost Analysis"
publication_sub_name: "England 2022/23"
publication_date: "8 June 2023"
responsible_statistician: "Graham Platten"
scotland_pca: "https://publichealthscotland.scot/media/14993/prescription_cost_analysis_2022.xlsx"
ni_pca: "https://hscbusiness.hscni.net/pdf/Prescription%20Cost%20Analysis%20-%202022.xlsx"
wa_pca: "Y:/Official Stats/PCA/data/PCA_Wales_202122.xlsx"
wa_pca_link: "https://www.gov.wales/sites/default/files/statistics-and-research/2022-09/prescriptions-summary-data-2001-02-to-2021-22-002.ods"
fy_nat_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_summary_tables_2022_23_v001.xlsx"
fy_icb_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_icb_summary_tables_2022_23_v001.xlsx"
add_anl_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_additional_tables_2022_23_v001.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/pca/pca_background_info_methodology_v001.html"
nhsbsa_pca_link: "https://www.nhsbsa.nhs.uk/prescription-data/dispensing-data/prescription-cost-analysis-pca-data"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
